### ISSUE TITLE
practica1

### ISSUE THREAD

**Issue by grupohernandezalba** [LuisZanella/GeoReferenciados#1]
Ya casi queda @LuisZanella   , solo me esta mandando un error puede ser la API KEY usa la que subí en el Drive Compatido http://bit.ly/sistemasgeo

**Comment by ZanellaStack** [comment]
Problema resuelto @grupohernandezalba, gracias! cualquier otra cosa estaré encantado de resolverla!! que tenga un buen día. 
![image](https://user-images.githubusercontent.com/34582787/76647790-1479aa80-6523-11ea-8dcb-13dea30ac1e1.png)
