### ISSUE TITLE
practicas

### ISSUE THREAD

**Issue by grupohernandezalba** [LuisZanella/GeoReferenciados#2]
Hola @LuisZanella  ya quedaron tus practicas muy buen trabajo.

Solo en el mapa de las practicas5 se sigue poniendo developer.

![Captura de Pantalla 2020-03-01 a la(s) 13 13 29](https://user-images.githubusercontent.com/14998558/75632119-a518c800-5bbe-11ea-9e77-1bcb2147360e.png)

**Comment by ZanellaStack** [comment]
Situación arreglada muchas gracias @grupohernandezalba, cualquier otra situación se agradecería!! que tenga un buen día 👍 :).
![Issue Practica 2 Resuelto](https://user-images.githubusercontent.com/34582787/76647680-e4320c00-6522-11ea-9f1a-341c8308b104.png)
