### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by grupohernandezalba** [LuisZanella/GeoReferenciados#3]
Muy bien Luis Edgar, fijate que no me funciono el borrado , checalo. Si te es posible trata de implementar la opción de editar.

![Captura de Pantalla 2020-03-12 a la(s) 22 15 09](https://user-images.githubusercontent.com/14998558/76589261-13a73100-64af-11ea-8494-31d17d6451e8.png)

**Comment by ZanellaStack** [comment]
Problema resuelto :)  y accion de editar agregada. Gracias, que tenga un buen día, cualquier situación más se agradece!!

**Comment by ZanellaStack** [comment]
![image](https://user-images.githubusercontent.com/34582787/76647853-33783c80-6523-11ea-813e-06d9aa91010e.png)
