### ISSUE TITLE
Aviso

### ISSUE THREAD

**Issue by grupohernandezalba** [LuisZanella/GeoReferenciados#4]
Hola @LuisZanella 

Anexo video de la clase del día de hoy 

Firebase practica2, se optimizo la practica1 agregando la opción de editar productos y usando POO.:

https://youtu.be/r1uSXT_2Qos

Las practicas ya están actualizadas en GitHub:
https://github.com/grupohernandezalba/sistemasgeo

Les recuerdo que los videos los pueden accesar también desde el drive compartido:

http://bit.ly/sistemasgeo

**Comment by ZanellaStack** [comment]
@grupohernandezalba  Hay algún problema si no agregamos el modal y solo hice lo de la practica pasada (ya le había implementado la opción de editar) pero ahora si con la Programación orientada a objetos de javascript?

**Comment by grupohernandezalba** [comment]
Esta perfecto así como lo mencionas Luis. No importa si no usas modal.





[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
18/03/20
22:47:01
